@startuml

title Guile-PNG Reader

[*] ---> read_header

read_header: Read and check PNG header.
read_header:
read_header: entry-action: read-header
read_header --> header_error: guard:context-has-errors?
read_header --> read_chunk

header_error: exit-action: header-error
header_error --> [*]

read_chunk: Read a PNG chunk.
read_chunk:
read_chunk: entry-action: read-chunk
read_chunk --> chunk_error: guard:context-has-errors?
read_chunk --> handle_chunk: guard:known-chunk?
read_chunk --> chunk_type_error

handle_chunk: entry-action: store-chunk
handle_chunk --> [*]: guard:iend-chunk?
handle_chunk --> read_chunk

chunk_type_error: exit-action: chunk-type-error
chunk_type_error --> [*]

chunk_error: exit-action: chunk-error
chunk_error --> [*]

@enduml