name: GNU Guile 2.2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install guile-2.2 guile-2.2-libs guile-library
          sudo apt install guile-2.2-dev texinfo gettext
          sudo apt install automake autoconf help2man texlive

      - name: Select Guile 2.2
        run: |
          echo 1 | sudo update-alternatives --config guile

      - name: Install Guile-ZLIB
        run: |
          wget -O guile-zlib.tar.gz https://archive.softwareheritage.org/api/1/vault/flat/swh:1:dir:c8686f5aaddec4650ceefa62b31df6e9eb40e085/raw/
          tar -zxf guile-zlib.tar.gz
          cd 'swh:1:dir:c8686f5aaddec4650ceefa62b31df6e9eb40e085'
          autoreconf -vif
          ./configure --with-guilesitedir=/usr/share/guile/site/2.2 --prefix=/usr
          sudo make -j$(nproc) install

      - name: Install Guile-SMC
        run: |
          git clone https://github.com/artyom-poptsov/guile-smc
          cd guile-smc
          git checkout master
          autoreconf -vif
          ./configure --with-guilesitedir=/usr/share/guile/site/2.2 --prefix=/usr
          sudo make -j$(nproc) install

      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Autoreconf
        run: autoreconf -vif

      - name: Configure
        run: ./configure

      - name: Build
        run: make -j$(nproc)

      - name: Test
        run: make -j$(nproc) check

      - name: Distcheck
        run: make -j$(nproc) distcheck

      - name: Upload the artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: guile-png
          compression-level: 0
          path: "guile-png-*.tar.gz"
